@*
    Files generated by SmartTools.Net Codeless
    $GenDate$
*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>$title$-详情</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link href="~/app/lib/layui-v2.5.4/css/layui.css" rel="stylesheet" />
    <link href="~/app/css/combo.css" rel="stylesheet" />
    <link href="~/app/css/combobox.css" rel="stylesheet" />
    <link href="~/app/css/textbox.css" rel="stylesheet" />
    <link href="~/app/css/common.single-page.opdialog-1.0.css" rel="stylesheet" />
    <link href="~/app/css/common-3.0.css" rel="stylesheet" />
</head>
<body>
    <form id="DetailForm" class="layui-form drawer-form" onkeydown="if(event.keyCode==13){return false}">
        <div>

            $formArea$

        </div>
    </form>

    <script src="~/app/js/jquery.min.js"></script>
    <script src="~/app/lib/layui-v2.5.4/layui.js"></script>
    <script src="~/app/js/language.js"></script>

    <script>
        layui.use(['form', 'layer'], function () {
            var form = layui.form,
                layer = layui.layer;
            active = {
                cancel: function () {
                    var index = parent.layer.getFrameIndex(window.name);
                    parent.layer.close(index);
                },
                init: function () {
                    $('.layui-btn').on('click', function () {
                        var type = $(this).data('type');
                        active[type] ? active[type].call(this) : '';
                    })

                    /********************此处为初始化渲染示例，请根据实际业务调整 begin********************/
                    /********************SmartTools.Net Codeless********************/

                    //数字格式化
                    /*
                    $("#ExtQty").val(parseFloat('Model.Qty'))
                    */

                    /********************此处为初始化渲染示例，请根据实际业务调整 end********************/
                },
            }
            active.init()
        });
    </script>
</body>
</html>