/*
 * Files generated by SmartTools.Net Codeless
 * $GenDate$
 *
 */

using System;
using System.ComponentModel.DataAnnotations;
using Longnows.Saas.Framework.Common.Base;
using Longnows.Saas.Framework.Common.Attributes;

namespace $Rootnamespace$
{
    [TableColumnMapper]
    public class $ModelName$ : BaseEntityDto
    {
		$EntityField$
    }
}