@*
    Files generated by SmartTools.Net Codeless
    $GenDate$
*@

<!DOCTYPE html>
<html>
<head>
    <title>$title$</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="format-detection" content="telephone=no">
    <link href="~/app/lib/layui-v2.5.4/css/layui.css" rel="stylesheet" />
    <link href="~/app/css/combo.css" rel="stylesheet" />
    <link href="~/app/css/combobox.css" rel="stylesheet" />
    <link href="~/app/css/textbox.css" rel="stylesheet" />
    <link href="~/app/css/common-Table-page-2.0.css" rel="stylesheet" />
    <link href="~/app/css/common-3.0.css" rel="stylesheet" />
    <link href="~/app/lib/iconfont/iconfont.css" rel="stylesheet" />
</head>

<body>
    <div class="layui-collapse" lay-filter="search-container">
        <div class="layui-colla-item">
            <h2 class="layui-colla-title">
                查询区域
            </h2>
            <div class="layui-colla-content layui-show" style="border:none;">

                $searchArea$

                <div class="layui-row" style="border-bottom:none;">
                    <div class="layui-col-md12 layui-col-sm12" style="text-align:center;padding-top:10px;border-left:none;">
                        <lg:btn title="查询" action='$privilege$/search' data-type='search' class="layui-btn layui-btn-sm layui-bg-blue table_btn"></lg:btn>
                        <lg:btn title="重置" action='$privilege$/reset' data-type='reset' class="layui-btn layui-btn-sm layui-btn-primary table_btn"></lg:btn>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="layui-table" id="tab_container" lay-filter="tab_container" lay-data="{  height: 'full-169',loading:false, limit: 100,  limits: limits, page: true, toolbar: '#tool_bar',defaultToolbar:['filter']}">
        <thead>
            <tr>
                <th lay-data="{checkbox:true, fixed:'left', width: 50}"></th>
                <th lay-data="{type:'numbers', fixed:'left', width: 50}">序号</th>

                $tableFields$

                <th lay-data="{field: 'right', width: 140, align:'center', toolbar: '#barDemo',fixed:'right'}">操作</th>
            </tr>
        </thead>
    </table>
</body>
</html>

<!--抽屉式弹框-->
<div class="slider">
    <div class="trigger">
        <i class="layui-icon layui-icon-spread-left">
            <span id="titleSpan"
                style="font-weight: bold;
                font-size: 14px;
                color: #666;
                overflow: hidden;">
            </span>
        </i>
    </div>
    <iframe id="mainFrame" name="mainFrame" src="" style="width:100%;height:100%" scrolling="yes" frameborder="0" border="0" marginwidth="0" marginheight="0">
    </iframe>
</div>

<div class="shade"></div>

<script type="text/html" id="tool_bar">
    <div class="layui-btn-group">
        <lg:import action='$privilege$/import' download-url='/Template/Import/GalaxyCore/导入模板_采购订单.xlsx' event='import'></lg:import>
        <lg:add action='$privilege$/create' event='create'></lg:add>
        <lg:del action='$privilege$/delete' event='delete'></lg:del>
        @*<lg:edit action='$privilege$/edit' event='edit'></lg:edit>*@
        @*<lg:detail action='$privilege$/details' event='details'></lg:detail>*@
        <lg:dropdown title="导出" event="export" items='@new List<DropdownItem>() {
                     new DropdownItem("批量导出","$privilege$/exporttoexcel","0"),
                     new DropdownItem("勾选导出","$privilege$/exporttoexcelbyids","1")}'>
        </lg:dropdown>
    </div>
</script>

<script type="text/html" id="barDemo">
    <lg:editicon action="$privilege$/edit" event="edit"></lg:editicon>
    <lg:detailicon action="$privilege$/details" event="details"></lg:detailicon>
    <lg:delicon action="$privilege$/delete" event="delete"></lg:delicon>
</script>

<script src="~/app/js/jquery.min.js"></script>
<script src="~/app/lib/layui-v2.5.4/layui.js"></script>
<script src="~/app/js/jquery.validate.min.js"></script>
<script src="~/app/js/common-3.0.js"></script>
<script src="~/app/js/easyloader.js"></script>
<script src="~/app/js/jquery.parser.js"></script>
<script src="~/app/js/jquery.linkbutton.js"></script>
<script src="~/app/js/jquery.panel.js"></script>
<script src="~/app/js/jquery.validatebox.js"></script>
<script src="~/app/js/jquery.tooltip.js"></script>
<script src="~/app/js/jquery.textbox.js"></script>
<script src="~/app/js/jquery.combo.js"></script>
<script src="~/app/js/jquery.combobox.js"></script>
<script src="~/app/js/language.js"></script>

<script>

    function PrefixInteger(num, n) {
        return (Array(n).join(0) + num).slice(-n);
    }

   layui.use(['layer', 'upload', 'table', 'laydate', 'jquery','element'], function () {
        var $ = layui.jquery,
            table = layui.table
        layer = layui.layer
        upload = layui.upload
        element = layui.element;
        var laydate = layui.laydate;

        /********************此处为日期初始化示例，请根据实际业务调整 begin********************/
        /********************SmartTools.Net Codeless********************/

        var beginDate = '@DateTime.Now.ToString("yyyy-MM-01")';
        var endDate = '@DateTime.Now.ToString("yyyy-MM-dd")';
        var _beginDate = beginDate;
        var _endDate = endDate;

        /********************此处为日期初始化示例，请根据实际业务调整 end********************/

        element.on('collapse(search-container)', function (data) {
            if (data.show) {
                table.reload("tab_container", { height: "full-169" })
            } else {
                table.reload("tab_container", { height: "full-55" })
            }
        });

        /********************此处为日期弹框渲染示例，请根据实际业务调整 begin********************/
        /********************SmartTools.Net Codeless********************/

        /*laydate.render({
            elem: "#xxx",
            value:  beginDate+" ~ "+ endDate,
            trigger: 'click',
            range: "~",
            done: function (value, date, endDate) {
                _beginDate = date.year + "-" + PrefixInteger(date.month, 2) + "-" + PrefixInteger(date.date, 2);
                _endDate = endDate.year + "-" + PrefixInteger(endDate.month, 2) + "-" + PrefixInteger(endDate.date, 2);
            }
        })*/

        /********************此处为日期弹框渲染示例，请根据实际业务调整 end********************/

        $(".shade").click(function () {
            active.closeSlider();
        })

        $(".trigger").click(function () {
            active.closeSlider();
        })

       active = {
            //打开右侧滑块
            openSlider: function () {
                $(".slider").removeClass("close")
                $(".slider").toggleClass("open");
                $(".shade").css('display', 'block')
                $(".trigger i").toggleClass("layui-icon-shrink-right")
                $(".trigger i").removeClass("layui-icon-spread-left")
            },

            //关闭右侧滑块
            closeSlider: function () {
                $(".slider").removeClass("open");
                $(".slider").toggleClass("close");
                $(".shade").css('display', 'none');
                $(".trigger i").removeClass("layui-icon-shrink-right");
                $(".trigger i").toggleClass("layui-icon-spread-left");
            },

            //导入
            import: function () {
                var title = $(this).attr('lg-action');
                var url = $(this).attr('lg-action');
                var downloadUrl = $(this).attr('lg-downloadurl');
                $.importDialog.show('导入', 'Import', downloadUrl, function (data) {
                    if (data) {
                        if (data.Success) {
                            showLayerMsg("导入成功", 2000)
                            active.search()
                        } else {
                            var message = (data.Message == null ? "" : data.Message) + (data.Data == null ? "" : data.Data);
                            showLayerAlert('导入失败：' + message);
                        }
                    } else {
                        showLayerAlert('导入失败：请联系管理员');
                    }
                })
            },

            //新增
            create: function () {
                //LayerOpen('Create', '采购订单-新增', '665px', '315px', '')
                $("#titleSpan").text(" $title$-新增")
                document.getElementById("mainFrame").src = "$privilege$/Create"
                active.openSlider();
            },

            //修改
            edit: function () {
                var rows = table.checkStatus('tab_container').data;
                if (rows.length != 1) {
                    showLayerAlert('请选择一行数据进行修改！')
                    return false;
                }
                if (rows[0].ExtFlagName == "已提取") {
                    showLayerAlert('已提取的数据不允许修改！')
                    return false;
                }
                LayerOpen('Edit?SeqNo=' + rows[0]['SeqNo'], '采购订单-修改', '665px','315px')
            },

            //行内修改
            editInline: function (data) {
               if (data.ExtFlagName == "已提取") {
                    showLayerAlert('已提取的数据不允许修改！')
                    return false;
               }
               $("#titleSpan").text(" $title$-修改")
               document.getElementById("mainFrame").src = "$privilege$/Edit?SeqNo=" + data.SeqNo
               active.openSlider();
            },

            //删除
            delete: function (data) {
                var rows = table.checkStatus('tab_container').data;
                var keys = [];
                if (rows.length == 0) {
                    showLayerAlert('请至少选择一条数据删除')
                    return
                } else {
                    for (var i = 0; i < rows.length; i++) {
                        keys.push(rows[i]['SeqNo'])

                        /********************此处为删除前校验，请根据实际业务调整 begin********************/
                        /********************SmartTools.Net Codeless********************/

                        /*if (rows[i].xxx == "xxx") {
                            showLayerAlert('xxx不允许删除！');
                            return false;
                        }*/

                        /********************此处为删除前校验，请根据实际业务调整 end********************/
                    }
                    layer.open({
                        content: '确定要删除吗？',
                        btn: ['确认', '取消'],
                        yes: function (index, layero) {
                            var _index = showLoading()
                            $.ajax({
                                type: 'POST',
                                url: 'Delete',
                                data: { keys: keys },
                                dataType: 'json',
                                success: function (result) {
                                    hideLoading(_index)
                                    if (result.Success) {
                                        layer.alert('删除成功！', { icon: 1, closeBtn: 0, title: '系统提示' }, function (index) {
                                            layer.close(index);
                                            active.search()
                                        });
                                    } else {
                                        layer.alert('删除失败！' + result.Message, { icon: 2, closeBtn: 0, title: '系统提示' }, function (index) {
                                            layer.close(index);
                                        });
                                    }
                                },
                                error: function (e) {
                                    hideLoading(_index)
                                    layer.alert('删除失败！' + e.status, { icon: 2, closeBtn: 0, title: '系统提示' }, function (index) {
                                        layer.close(index);
                                    })
                                }
                            })
                        }
                    })
                }
            },

            //行内删除
            deleteInline: function (data) {
               /********************此处为删除前校验，请根据实际业务调整 begin********************/
               /********************SmartTools.Net Codeless********************/

                    //if (data.xxx == "xxx") {
                        //showLayerAlert('xxx不允许删除！');
                        //return false;
                    //}

                /********************此处为删除前校验，请根据实际业务调整 end********************/

                var keys = [];
                keys.push(data.SeqNo);
                layer.open({
                        content: '确定要删除吗？',
                        btn: ['确认', '取消'],
                        yes: function (index, layero) {
                            var _index = showLoading()
                            $.ajax({
                                type: 'POST',
                                url: 'Delete',
                                data: { keys: keys },
                                dataType: 'json',
                                success: function (result) {
                                    hideLoading(_index)
                                    if (result.Success) {
                                        layer.alert('删除成功！', { icon: 1, closeBtn: 0, title: '系统提示' }, function (index) {
                                            layer.close(index);
                                            active.search()
                                        });
                                    } else {
                                        layer.alert('删除失败！' + result.Message, { icon: 2, closeBtn: 0, title: '系统提示' }, function (index) {
                                            layer.close(index);
                                        });
                                    }
                                },
                                error: function (e) {
                                    hideLoading(_index)
                                    layer.alert('删除失败！' + e.status, { icon: 2, closeBtn: 0, title: '系统提示' }, function (index) {
                                        layer.close(index);
                                    })
                                }
                            })
                        }
                    })
            },

            //详情
            details: function () {
                var rows = table.checkStatus('tab_container').data;
                if (rows.length != 1) {
                    showLayerAlert('请选择一行数据进行查看！')
                    return false
                }
                LayerOpen('Details?SeqNo=' + rows[0]['SeqNo'], '$title$-详情', '665px', '315px')
            },

            //行内详情
            detailsInline: function (data) {
                $("#titleSpan").text("$title$-详情")
                document.getElementById("mainFrame").src = "$privilege$/Details?SeqNo=" + data.SeqNo
                active.openSlider();
            },

            //导出
            export: function (data) {

                //判断按钮
                var downloadUrl = $(this).attr('lg-downloadurl');
                var index = showLoading()
                var rows = table.checkStatus('tab_container').data;

                //批量导出
                if (downloadUrl == "0") {
                    $.ajax({
                        type: 'POST',
                        url: 'ExportToExcel',
                        data: active.getQuery(),
                        dataType: 'json',
                        success: function (result) {
                            hideLoading(index)
                            if (result.Success) {
                                showLayerMsg('操作成功', 2000)
                                window.location.href = result.Data;
                            } else {
                                showLayerAlert('操作失败：' + result.Message);
                            }
                        },
                        error: function (e) {
                            hideLoading(index)
                            showLayerAlert('操作失败：' + e.status)
                        }
                    })
                }

                //勾选导出
                else if (downloadUrl == "1") {
                    if (rows.length == 0) {
                        hideLoading(index)
                        showLayerAlert('请至少选择一行数据导出！')
                        return;
                    }
                    var keys = [];
                    for (var i = 0; i < rows.length; i++) {
                        keys.push(rows[i]['SeqNo'])
                    }
                    $.ajax({
                        type: 'POST',
                        url: 'ExportToExcelByIds',
                        data: { keys: keys },
                        dataType: 'json',
                        success: function (result) {
                            hideLoading(index)
                            if (result.Success) {
                                showLayerMsg('操作成功', 2000)
                                window.location.href = result.Data;
                            } else {
                                showLayerAlert('操作失败：' + result.Message);
                            }
                        },
                        error: function (e) {
                            hideLoading(index)
                            showLayerAlert('操作失败：' + e.status)
                        }
                    })
                }
            },

            //获取查询参数
            /********************此处为获取值示例，请根据实际业务调整 begin********************/
            /********************SmartTools.Net Codeless********************/
            /*
                【输入框获取值】
                xxx: $('#xxx').val()

                【下拉框获取值】
                xxx: $('#xxx').combobox('getValue')

                【日期范围获取值】
                BeginDate: ($('#SearchDate').val() == null || $('#SearchDate').val() == '') ? null : $('#SearchDate').val().split("~")[0],
                EndDate: ($('#SearchDate').val() == null || $('#SearchDate').val() == '') ? null : $('#SearchDate').val().split("~")[1],
            */
            /********************此处为获取值示例，请根据实际业务调整 end********************/
            getQuery: function () {
                return {
                    rdt: new Date().getTime(),
                    $queryParam$
                }
            },

            //查询
            search: function () {
                var index = showLoading()
                table.reload('tab_container', {
                    page: {
                        curr:1
                    },
                    method: 'post',
                    url: 'Search'
                    , where: active.getQuery()
                    , done: function () {
                        hideLoading(index)
                    }
                });
            },

            //重置查询条件
            /********************此处为重置示例，请根据实际业务调整 begin********************/
            /********************SmartTools.Net Codeless********************/
            /*
                【输入框重置】
                xxx: $('#xxx').val('');

                【下拉框重置】
                xxx: $('#xxx').combobox('setValue', '');

                【日期范围重置】
                $("#SearchDate").val(beginDate + " ~ " + endDate);
                _beginDate = beginDate;
                _endDate = endDate;

            */
            /********************此处为重置示例，请根据实际业务调整 end********************/
            reset: function () {
                $resetParam$
            },

            //初始化
            init: function () {
                $(".lg-combobox").lgcombobox();

                $('.layui-btn').on('click', function () {
                    var type = $(this).attr('data-type');
                    active[type] ? active[type].call(this) : '';
                })

                $('.layui-btn').on('click', function () {
                    var type = $(this).attr('lay-event');
                    active[type] ? active[type].call(this) : '';
                })

                $('.layui-import>dl>dd').on('click', function () {
                    var type = $(this).attr('lg-downloadurl');
                    active[type] ? active[type].call(this) : '';
                })

                table.on('toolbar(tab_container)', function (obj) {
                    var type = obj.event;
                    active[type] ? active[type].call(this) : '';
                })

                table.on('tool(tab_container)', function (obj) {
                    var data = obj.data;
                    var type = obj.event; //获得 lay-event 对应的值
                    switch (type) {
                        case 'edit':
                            active.editInline(data)
                            break;
                        case 'details':
                            active.detailsInline(data)
                            break;
                        case 'delete':
                            active.deleteInline(data)
                            break;
                        default:
                    }
                })

                if ($(".layui-collapse")[0].offsetHeight != 0) {
                    $("#tab_container").tableSizeInit({
                        "table": table,
                        getHeight: function () {
                            return $(".layui-collapse")[0].offsetHeight + 15;
                        }
                    })
                }

                /********************此处为示例初始化，请根据实际业务调整 begin********************/
                /********************SmartTools.Net Codeless********************/

                /*InitCommbox('xxx', null, [
                    { Code: '', Name: '全部', Text: '全部'},
                    { Code: '0', Name: 'xxx', Text: 'xxx','selected':true },
                    { Code: '1', Name: 'xxx', Text: 'xxx' }
                ])*/

                //$("#xxx").val(beginDate + " ~ " + endDate);

                /********************此处为示例初始化，请根据实际业务调整 end********************/

                active.search();
            }
        }

        active.init();
    })

    //日期格式化
    function LayuiDateFormatter(value) {
        if (value) {
            try {
                var d = new Date(value);
                return (eval(d)).pattern("yyyy-MM-dd");
            }
            catch (e) {
                return "";
            }
        }
        return "";
    }

</script>

@********************此处为模板渲染，请根据实际业务调整 begin********************@
@********************SmartTools.Net Codeless********************@

<script type="text/html" id="tplxxx">
    {{  LayuiDateFormatter(d.xxx) }}
</script>

@********************此处为模板渲染，请根据实际业务调整 end********************@