/*
 * Files generated by SmartTools.Net Codeless
 * $GenDate$
 *
 */

using System;
using idp_wechat.Models;
using System.ComponentModel.DataAnnotations;

namespace $Rootnamespace$
{
    public class $ModelName$SearchDto: CoreBaseSearch
    {
        $EntityField$
    }
}
