/*
 * Files generated by SmartTools.Net Codeless
 * $GenDate$
 *
 */

using System;
using System.ComponentModel.DataAnnotations;

namespace $Rootnamespace$
{
    public class $ModelName$
    {
		$EntityField$
    }
}